---
apiVersion: v1
kind: Service
metadata:
  name: Custom-Portal
  labels:
    app: Custom-Portal
spec:
  type: NodePort
  selector:
    app: Custom-Portal
  ports:
  - protocol: TCP
    port: 8010
    name: http

---
apiVersion: v1
kind: ReplicationController
metadata:
  name: Custom-Portal
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: Custom-Portal
    spec:
      containers:
      - name: Custom-Portal
        image: image-registry.openshift-image-registry.svc:5000/kubetime-tekton/custom-portal:latest
        ports:
        - containerPort: 8010
        livenessProbe:
          httpGet:
            path: /health
            port: 8010
          initialDelaySeconds: 30
          timeoutSeconds: 1
