apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-api
  template:
    metadata:
      labels:
        app: vote-api
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - name: api
        image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: vote-api
  annotations:
    dev.okteto.com/auto-ingress: "true"
  labels:
    app: vote-api
spec:
  type: ClusterIP
  ports:
    - name: vote-api
      port: 8080
  selector:
    app: vote-api
